module com.bgconsole.desktop_ui {
    requires javafx.controls;
    requires javafx.fxml;
    requires com.kodedu.terminalfx;
//    requires com.fasterxml.jackson.dataformat.yaml;
    requires org.apache.commons.lang3;
//    requires com.fasterxml.jackson.;
//    requires jnativehook;
    requires java.logging;
    requires simplenativehooks;
    requires javafx.base;
    requires kotlin.stdlib;
    requires com.bgconsole.domain;
    requires com.bgconsole.core;
    requires com.bgconsole.desktop_engine;
    requires annotations;

    opens com.bgconsole.desktop_ui to javafx.fxml;
    opens com.bgconsole.desktop_ui.ui.vareditor to javafx.fxml;
    opens com.bgconsole.desktop_ui.ui.commandeditor to javafx.fxml;
    opens com.bgconsole.desktop_ui.ui.terminal_window to javafx.fxml;
    opens com.bgconsole.desktop_ui.ui.profile to javafx.fxml;
    opens com.bgconsole.desktop_ui.ui.global_window to javafx.fxml, javafx.base;
    opens com.bgconsole.desktop_ui.workspace to com.fasterxml.jackson.databind;
    exports com.bgconsole.desktop_ui;
    exports com.bgconsole.desktop_ui.variable;
    exports com.bgconsole.desktop_ui.command;
    exports com.bgconsole.desktop_ui.config;
    exports com.bgconsole.desktop_ui.terminal;
    exports com.bgconsole.desktop_ui.environment;
    exports com.bgconsole.desktop_ui.global_input;
    exports com.bgconsole.desktop_ui.location;
    exports com.bgconsole.desktop_ui.workspace;
    exports com.bgconsole.desktop_ui.project;
    exports com.bgconsole.desktop_ui.profile;
    exports com.bgconsole.desktop_ui.ui.terminal_window;
    opens com.bgconsole.desktop_ui.global_input to javafx.fxml;
    exports com.bgconsole.desktop_ui.ui.new_location;
    opens com.bgconsole.desktop_ui.ui.new_location to javafx.fxml;
    opens com.bgconsole.desktop_ui.ui.new_project to javafx.fxml;
    exports com.bgconsole.desktop_ui.main_window;
    opens com.bgconsole.desktop_ui.main_window to javafx.fxml;
}